from PyQt6 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 542)
        MainWindow.setStyleSheet("QPushButton{\n"
"    border : none;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.head = QtWidgets.QFrame(parent=self.centralwidget)
        self.head.setStyleSheet("background-color: rgb(42, 61, 81);")
        self.head.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.head.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.head.setObjectName("head")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.head)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.head_l = QtWidgets.QFrame(parent=self.head)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.head_l.sizePolicy().hasHeightForWidth())
        self.head_l.setSizePolicy(sizePolicy)
        self.head_l.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.head_l.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.head_l.setObjectName("head_l")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.head_l)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.books_btn = QtWidgets.QPushButton(parent=self.head_l)
        self.books_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icon/docs.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.books_btn.setIcon(icon)
        self.books_btn.setIconSize(QtCore.QSize(32, 32))
        self.books_btn.setObjectName("books_btn")
        self.gridLayout_2.addWidget(self.books_btn, 2, 5, 1, 1)
        self.down_btn = QtWidgets.QPushButton(parent=self.head_l)
        self.down_btn.setEnabled(True)
        self.down_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./icon/要求.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.down_btn.setIcon(icon1)
        self.down_btn.setIconSize(QtCore.QSize(32, 32))
        self.down_btn.setAutoDefault(False)
        self.down_btn.setDefault(False)
        self.down_btn.setObjectName("down_btn")
        self.gridLayout_2.addWidget(self.down_btn, 2, 7, 1, 1)
        self.open_btn = QtWidgets.QPushButton(parent=self.head_l)
        self.open_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./icon/file_open.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.open_btn.setIcon(icon2)
        self.open_btn.setIconSize(QtCore.QSize(32, 32))
        self.open_btn.setObjectName("open_btn")
        self.gridLayout_2.addWidget(self.open_btn, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.head_l, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.head_r = QtWidgets.QFrame(parent=self.head)
        self.head_r.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.head_r.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.head_r.setObjectName("head_r")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.head_r)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.setting_btn = QtWidgets.QPushButton(parent=self.head_r)
        self.setting_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./icon/齿轮.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.setting_btn.setIcon(icon3)
        self.setting_btn.setIconSize(QtCore.QSize(26, 26))
        self.setting_btn.setObjectName("setting_btn")
        self.horizontalLayout_2.addWidget(self.setting_btn)
        self.minimize_window = QtWidgets.QPushButton(parent=self.head_r)
        self.minimize_window.setText("")


        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./icon/缩小.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimize_window.setIcon(icon4)
        self.minimize_window.setObjectName("minimize_window")
        self.horizontalLayout_2.addWidget(self.minimize_window)
        self.restore_window = QtWidgets.QPushButton(parent=self.head_r)
        self.restore_window.setText("")

        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./icon/正方形.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.restore_window.setIcon(icon5)
        self.restore_window.setObjectName("restore_window")
        self.horizontalLayout_2.addWidget(self.restore_window)
        self.close_window = QtWidgets.QPushButton(parent=self.head_r)
        self.close_window.setText("")

        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./icon/关闭.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close_window.setIcon(icon6)
        self.close_window.setObjectName("close_window")

        # 連接信號和槽
        self.minimize_window.clicked.connect(MainWindow.showMinimized)
        self.restore_window.clicked.connect(self.toggleMaxRestore)
        self.close_window.clicked.connect(MainWindow.close)




        self.horizontalLayout_2.addWidget(self.close_window)
        self.horizontalLayout.addWidget(self.head_r, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout.addWidget(self.head, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.mian = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mian.sizePolicy().hasHeightForWidth())
        self.mian.setSizePolicy(sizePolicy)
        self.mian.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.mian.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mian.setObjectName("mian")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.mian)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.mian)
        self.stackedWidget.setObjectName("stackedWidget")
        self.setting = QtWidgets.QWidget()
        self.setting.setObjectName("setting")
        self.frame = QtWidgets.QFrame(parent=self.setting)
        self.frame.setGeometry(QtCore.QRect(180, 60, 121, 341))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.pushButton = QtWidgets.QPushButton(parent=self.setting)
        self.pushButton.setGeometry(QtCore.QRect(430, 410, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./icon/保存.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.frame_2 = QtWidgets.QFrame(parent=self.setting)
        self.frame_2.setGeometry(QtCore.QRect(300, 60, 371, 341))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 341, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 90, 341, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 160, 341, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 220, 341, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 290, 301, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 290, 75, 24))
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.setting)
        self.books = QtWidgets.QWidget()
        self.books.setObjectName("books")
        self.label_6 = QtWidgets.QLabel(parent=self.books)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.treeWidget_2 = QtWidgets.QTreeWidget(parent=self.books)
        self.treeWidget_2.setGeometry(QtCore.QRect(10, 30, 831, 451))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_2.setFont(font)
        self.treeWidget_2.setObjectName("treeWidget_2")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_2.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_2.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_2.headerItem().setFont(2, font)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.books)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 10, 75, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.treeWidget_2.raise_()
        self.label_6.raise_()
        self.pushButton_3.raise_()
        self.stackedWidget.addWidget(self.books)
        self.down = QtWidgets.QWidget()
        self.down.setObjectName("down")
        self.label_7 = QtWidgets.QLabel(parent=self.down)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.treeWidget = QtWidgets.QTreeWidget(parent=self.down)
        self.treeWidget.setGeometry(QtCore.QRect(10, 30, 831, 451))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.setFont(font)
        self.treeWidget.setObjectName("treeWidget")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.headerItem().setFont(2, font)
        self.stackedWidget.addWidget(self.down)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.mian)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "網址 :"))
        self.label_4.setText(_translate("MainWindow", "根目錄 :"))
        self.label_2.setText(_translate("MainWindow", "帳號 :"))
        self.label_3.setText(_translate("MainWindow", "密碼 :"))
        self.label_5.setText(_translate("MainWindow", "本地下載路徑 :"))
        self.pushButton.setText(_translate("MainWindow", " 保存"))
        self.lineEdit.setText(_translate("MainWindow", "https.//tv-cp.snm0516.aisee.tv/v2/#/login"))
        self.lineEdit_2.setText(_translate("MainWindow", "国际版漫画 "))
        self.lineEdit_3.setText(_translate("MainWindow", "Renta"))
        self.lineEdit_4.setText(_translate("MainWindow", "Renta&Bilibili Comics-2024 "))
        self.label_6.setText(_translate("MainWindow", "下載清單"))
        self.treeWidget_2.headerItem().setText(0, _translate("MainWindow", "作品"))
        self.treeWidget_2.headerItem().setText(1, _translate("MainWindow", "結尾目錄"))
        self.treeWidget_2.headerItem().setText(2, _translate("MainWindow", "數量"))
        self.pushButton_3.setText(_translate("MainWindow", "開始下載"))
        self.label_7.setText(_translate("MainWindow", "書單管理"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "作品"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "結尾目錄"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "數量"))

    def toggleMaxRestore(self):
        if self.restore_window.window().isMaximized():
            self.restore_window.window().showNormal()
        else:
            self.restore_window.window().showMaximized()    
        
def main():
    import sys
    app = QtWidgets.QApplication(sys.argv)  # 創建一個 QApplication 實例
    MainWindow = QtWidgets.QMainWindow()     # 創建一個 QMainWindow 實例
    ui = Ui_MainWindow()                     # 創建 Ui_MainWindow 的實例
    ui.setupUi(MainWindow)                   # 設置 GUI
    MainWindow.show()                        # 顯示窗口
    sys.exit(app.exec())                     # 運行應用程序並等待窗口關閉

if __name__ == "__main__":
    main()
