# Generated by Django 4.2.5 on 2023-09-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(choices=[('中国', '中国'), ('台湾', '台湾'), ('日本', '日本'), ('美国', '美国')], max_length=10, verbose_name='合作地區')),
                ('status', models.CharField(choices=[('进行中', '进行中'), ('到期', '到期')], max_length=10, verbose_name='狀態')),
                ('shelf_name', models.CharField(max_length=55)),
                ('advance_payment', models.IntegerField(default=0)),
                ('fees_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='手續費百分比 (%)')),
                ('ratio_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='拆分比 (%)')),
                ('cycle_months', models.IntegerField(default=0)),
                ('exchange_rate_method', models.CharField(choices=[('中间价', '中间价'), ('汇款买入价', '汇款买入价'), ('汇款卖出价', '汇款卖出价')], max_length=10, verbose_name='匯率方式')),
                ('renewal_time', models.DateField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('mark', models.CharField(max_length=255)),
            ],
        ),
    ]
