# Generated by Django 4.2.5 on 2023-09-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0002_delete_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='出版社名稱')),
                ('area', models.CharField(choices=[('中国', '中国'), ('台湾', '台湾'), ('日本', '日本'), ('美国', '美国')], max_length=10, verbose_name='合作地區')),
                ('status', models.CharField(choices=[('进行中', '进行中'), ('到期', '到期')], max_length=10, verbose_name='狀態')),
                ('shelf_name', models.CharField(max_length=55, null=True, blank=True, verbose_name='上架出版社名稱')),
                ('advance_payment', models.IntegerField(default=0, verbose_name='保底金')),
                ('fees_percentage', models.DecimalField(decimal_places=3, max_digits=5, null=True, blank=True, verbose_name='手續費百分比 (%)')),
                ('ratio_percentage', models.DecimalField(decimal_places=3, max_digits=5, null=True, blank=True, verbose_name='拆分比 (%)')),
                ('cycle_months', models.IntegerField(default=0, verbose_name='付款週期(月)')),
                ('exchange_rate_method', models.CharField(choices=[('无', '无'), ('中间价', '中间价'), ('汇款买入价', '汇款买入价'), ('汇款卖出价', '汇款卖出价')], max_length=10, verbose_name='匯率方式')),
                ('renewal_time', models.DateField(null=True, blank=True, verbose_name='續簽時間')),
                ('start_time', models.DateField(null=True, blank=True, verbose_name='合作開始時間')),
                ('end_time', models.DateField(null=True, blank=True, verbose_name='合作結束時間')),
                ('mark', models.CharField(max_length=255, null=True, blank=True, verbose_name='註記')),
            ],
        ),
    ]
