# Generated by Django 4.2.5 on 2023-09-19 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_custommodelname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomModelName',
        ),
    ]
